name: Triggered Workflow

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job runs when the Main Workflow completes."
